language: python
python:
  - "2.7.12"
# command to install dependencies
install:
  - pip install virtualenv
  - pip install awscli
  - virtualenv custodian
  - source custodian/bin/activate
  - pip install c7n
script:
  - cd custodian
  - ls
